# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "blowfish"
baseURL = "https://frederik353.github.io/writeups/"
defaultContentLanguage = "en"
summaryLength = 30

enableRobotsTXT = true

[pagination]
pagerSize = 20

buildDrafts = false
buildFuture = false

enableEmoji = true

# Â googleAnalytics = "G-XXXXXXXXX"

[taxonomies]
  topic = "topics"
  ctf = "ctfs"
  tag = "tags"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'github-dark'

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
